name: Create Branch from Jira Issue

on:
  repository_dispatch:
    types: [jira-issue]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create branch from Jira issue
        run: |
          ISSUE_KEY=$(echo "${{ github.event.client_payload.issue.key }}" | grep -oE '[A-Z]+-[0-9]+')
          ISSUE_TITLE=$(echo "${{ github.event.client_payload.issue.fields.summary }}" | tr ' ' '-')
          BRANCH_NAME="feature/${ISSUE_KEY}-${ISSUE_TITLE}"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
